apiVersion: v1
kind: Pod
metadata:
  name: poc-index4
spec:  # specification of the pod's contents
  containers:
  - name: poc-index4
    image: "busybox"
    command: ["top"]
    stdin: true
    tty: true
---
apiVersion: v1
kind: Pod
metadata:
  name: poc
spec:  # specification of the pod's contents
  containers:
  - name: poc
    image: "busybox"
    command: ["top"]
    stdin: true
    tty: true
