steps:

# Fetch the KUBECONFIG file from GCS.
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://k8s-platform-master-$PROJECT_ID/admin.conf', './admin.conf' ]

# Push the configs.
#
# TODO: eliminate the need for the apply_k8s_workloads script by converting all
#       remaining pieces to jsonnet.
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mv admin.conf ./manage-cluster/
    mv ndt-tls ./manage-cluster/
    mv pusher.json ./manage-cluster/
    cd ./manage-cluster
    ./apply_k8s_workloads.sh $PROJECT_ID ./admin.conf
