steps:

# Fetch the KUBECONFIG file from GCS.
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://k8s-platform-master-$PROJECT_ID/admin.conf', './admin.conf' ]

# Fetch the NDT TLS files from GCS.
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', '-R', 'gs://k8s-platform-master-$PROJECT_ID/ndt-tls', '.']

# Fetch the Pusher JSON credentials from GCS.
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://k8s-platform-master-$PROJECT_ID/pusher-credentials.json', './pusher.json']

# Build the config.
- name: gcr.io/cloud-builders/go
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    go get github.com/google/go-jsonnet/cmd/jsonnet
    source manage-cluster/k8s_deploy.conf
    jsonnet prepare.jsonnet -o prepare.json
    jsonnet system.jsonnet -o system.json --ext-str PROJECT_ID --ext-str K8S_FLANNEL_VERSION


# Push the configs.
#
# TODO: eliminate the need for the apply_k8s_workloads script by converting all
#       remaining pieces to jsonnet.
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    kubectl apply -f prepare.json
    mv admin.conf ./manage-cluster/
    mv ndt-tls ./manage-cluster/
    mv pusher.json ./manage-cluster/
    cd ./manage-cluster
    ./apply_k8s_workloads.sh $PROJECT_ID ./admin.conf
    cd ..
    kubectl apply -f system.json

