steps:

# Create the image builder for later steps.
- name: gcr.io/cloud-builders/docker
  args: [
    'build', '-t', 'create_k8s_configs', '-f', 'manage-cluster/Dockerfile.create_k8s_configs', '.'
  ]

# Create the configs
- name: create_k8s_configs
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd ./manage-cluster
    ./create_k8s_configs.sh $PROJECT_ID

# Fetch the KUBECONFIG file from GCS.
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://k8s-platform-master-$PROJECT_ID/admin.conf', './admin.conf' ]

# Push the configs.
#
# TODO: eliminate the need for the apply_k8s_workloads script by converting all
#       remaining pieces to jsonnet.
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd ./manage-cluster
    ./apply_k8s_configs.sh $PROJECT_ID ../admin.conf
