apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fast-sidestream
  namespace: default
spec:
  selector:
    matchLabels:
      run: fast-sidestream
  template:
    metadata:
      labels:
        run: fast-sidestream
      annotations:
        # TODO: # enable when the tcp-info container has prometheus metrics.
        prometheus.io/scrape: 'false'
    spec:
      containers:
      - name: fast-sidestream
        image: measurementlab/tcp-info:latest
        volumeMounts:
        - name: fast-sidestream-data
          mountPath: /home
      - name: pusher
        image: measurementlab/pusher:latest
        env:
        - name: DIRECTORY
          value: /var/spool/fast-sidestream
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/credentials/pusher.json
        - name: BUCKET
          value: dropbox-mlab-sandbox
        - name: EXPERIMENT
          value: fast-sidestream
        # TODO: specify the node & site names using kubernetes magic.
        volumeMounts:
        - name: fast-sidestream-data
          mountPath: /var/spool/fast-sidestream
        - name: credentials
          mountPath: /etc/credentials
          readOnly: true
      volumes:
      - name: fast-sidestream-data
        hostPath:
          path: /cache/core/fast-sidestream
          type: DirectoryOrCreate
      - name: credentials
        secret:
          secretName: pusher-credentials

      hostNetwork: true
