---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flannel
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flannel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
- kind: ServiceAccount
  name: flannel
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  # This is the CNI config needed for the cloud machines.
  cloud-cni-conf.json: |
    {
      "name": "cbr0",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  # This is the CNI config needed for the platform nodes.
  # This file should not contain any index_to_ip stuff. It is the backup config
  # for when multus isn't working or a pod is not tagged with any network
  # stuff.  Multus is supposed to preferentially get its config data out of
  # etcd, but it can't connect to etcd from non-Master nodes for reasons
  # unknown (likely related to it having a RFC1918 address for its
  # "ExternalIP").
  # Currently has no index_to_ip stuff in it to aid debugging.
  # TODO: Fix the ability of multus to connect to etcd so we can delete the
  # ipvlan stuff.
  platform-node-cni-conf.json: |
    {
     "name": "multus-network",
     "type": "multus",
     "delegates": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": false
          },
          "masterplugin": true
        },
        {
          "name": "ipvlan",
          "type": "ipvlan",
          "master": "eth0",
          "ipam": {
            "type": "index2ip"
          }
        }
      ]
    }
# This is what we think the config should be.
#    {
#      "name": "multus-network",
#      "type": "multus",
#      "delegates": [
#        {
#          "type": "flannel",
#          "delegate": {
#            "hairpinMode": true,
#            "isDefaultGateway": false
#          },
#          "masterplugin": true
#        }      ]
#    }
  net-conf.json: |
    {
      "Network": "192.168.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
