apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: scamper
  namespace: default
volumeMounts:
  name: scamper-data
  mountPath: /var/spool/scamper/
  name: varlibdockercontainers
  mountPath: /var/lib/docker/containers
volumes:
  name: scamper-data
  hostPath:
    path: /cache/core/scamper
    type: DirectoryOrCreate
spec:
  selector:
    matchLabels:
      run: scamper
  template:
    metadata:
      labels:
        run: scamper
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      containers:
      - name: scamper
        image: measurementlab/scamper
      hostNetwork: true
      hostPID: true
