apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: scamper
  namespace: default
spec:
  selector:
    matchLabels:
      run: scamper
  template:
    metadata:
      labels:
        run: scamper
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      containers:
      - name: scamper
        image: measurementlab/scamper
        volumeMounts:
        - name: scamper-data
          mountPath: /var/spool/scamper/
      - name: pusher
        image: measurementlab/pusher:latest
        env:
        - name: DIRECTORY
          value: /var/spool/scamper
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/credentials/pusher.json
        - name: BUCKET
          value: dropbox-mlab-sandbox
        - name: EXPERIMENT
          value: scamper
        volumeMounts:
        - name: scamper-data
          mountPath: /var/spool/scamper
      volumes:
      - name: scamper-data
        hostPath:
          path: /cache/core/scamper
          type: DirectoryOrCreate

      hostNetwork: true
      hostPID: true
