apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: scamper
  namespace: default
spec:
  selector:
    matchLabels:
      run: scamper
  template:
    metadata:
      labels:
        run: scamper
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      containers:
      - name: scamper
        image: measurementlab/scamper
        volumeMounts:
        - name: scamper-data
          mountPath: /var/spool/scamper/
      volumes:
      - name: scamper-data
        hostPath:
          path: /cache/core/scamper
          type: DirectoryOrCreate

      hostNetwork: true
      hostPID: true
