apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-server
  labels:
    run: prometheus-server
spec:
  selector:
    matchLabels:
      run: prometheus-server
  template:
    metadata:
      labels:
        run: prometheus-server
      annotations:
        # Tell prometheus service discovery to scrape the pod containers.
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: prometheus
      nodeSelector:
        mlab/type: cloud
        node-role.kubernetes.io/master: ""

      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

      containers:
      - name: prometheus
        image: prom/prometheus:v2.4.2
        # TODO: enable longer retention once persistent volumes are available.
        #      "--storage.tsdb.retention=2880h",
        args: ["--config.file=/etc/prometheus/prometheus.yml",
               "--storage.tsdb.path=/prometheus",
               "--web.enable-lifecycle"]
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/
        #- name: prometheus-storage
        #  mountPath: /prometheus
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      # TODO: allocate an external PersistentDisk.
      #- name: prometheus-storage
      #  persistentVolumeClaim:
      #    claimName: auto-prometheus-disk0

      # TODO: allow service-specific entry points if possible.
      hostNetwork: true
