---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: flannel-conf
args: '{
         "cniVersion": "0.3.0",
         "type": "flannel",
         "delegate": {
           "hairpinMode": true,
           "isDefaultGateway": false
         },
         "masterplugin": true
       }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-1-conf
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-1",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 1
         }
       }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-2-conf
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-3",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 3
         }
       }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-4-conf
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-4",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 4
         }
       }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-5-conf
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-5",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 5
         }
       }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-6-conf
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-6",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 6
         }
       }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-7-conf
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-7",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 7
         }
       }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-8-conf
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-8",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 8
         }
       }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-9-conf
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-9",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 9
         }
       }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-10-conf
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-10",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 10
         }
       }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-11-conf
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-11",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 11
         }
       }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: index2ip-index-12-conf
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-12",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 12
         }
       }'
