---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: flannel-conf
plugin: flannel
args: '{
         "cniVersion": "0.3.0",
         "type": "flannel",
         "delegate": {
           "hairpinMode": true,
           "isDefaultGateway": false
         },
         "masterplugin": true
       }'
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: index2ip-index-1-conf
plugin: index2ip-index-1
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-1",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 1
         }
       }'
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: index2ip-index-2-conf
plugin: index2ip-index-2
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-2",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 2
         }
       }'
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: index2ip-index-3-conf
plugin: index2ip-index-3
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-3",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 3
         }
       }'
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: index2ip-index-4-conf
plugin: index2ip-index-4
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-4",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 4
         }
       }'
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: index2ip-index-5-conf
plugin: index2ip-index-5
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-5",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 5
         }
       }'
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: index2ip-index-6-conf
plugin: index2ip-index-6
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-6",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 6
         }
       }'
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: index2ip-index-7-conf
plugin: index2ip-index-7
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-7",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 7
         }
       }'
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: index2ip-index-8-conf
plugin: index2ip-index-8
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-8",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 8
         }
       }'
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: index2ip-index-9-conf
plugin: index2ip-index-9
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-9",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 9
         }
       }'
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: index2ip-index-10-conf
plugin: index2ip-index-10
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-10",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 10
         }
       }'
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: index2ip-index-11-conf
plugin: index2ip-index-11
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-11",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 11
         }
       }'
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: index2ip-index-12-conf
plugin: index2ip-index-12
args: '{
         "cniVersion": "0.3.0",
         "name": "ipvlan-index-12",
         "type": "ipvlan",
         "master": "eth0",
         "ipam": {
           "type": "index2ip",
           "index": 12
         }
       }'
