---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: flannel-conf
plugin: flannel
args: '[ {
           "type": "flannel",
           "delegate": {
             "hairpinMode": true,
             "isDefaultGateway": false
           },
           "masterplugin": true
         } ]'
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
 name: index2ip-conf
plugin: index2ip
args: '[ {
           "name": "ipvlan",
           "type": "ipvlan",
           "master": "eth0",
           "ipam": {
             "type": "index2ip"
           }
         } ]'
