apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ndt-cloud-index2
  namespace: default
spec:
  selector:
    matchLabels:
      run: ndt-cloud
  template:
    metadata:
      labels:
        run: ndt-cloud
      annotations:
        prometheus.io/scrape: 'true'
        networks: '[
          { "name": "flannel-conf" },
          { "name": "index2ip-conf" } ]'
    spec:

      # The default grace period after k8s sends SIGTERM is 30s. We extend the
      # grace period to give time for the following shutdown sequence. After the
      # grace period, kubernetes sends SIGKILL.
      #
      # NDT pod shutdown sequence:
      #
      #  * k8s sends SIGTERM to NDT server
      #  * NDT server enables lame duck status
      #  * monitoring reads lame duck status (60s max)
      #  * mlab-ns updates server status (60s max)
      #  * all currently running tests complete. (30s max)
      #
      # TODO: enable before receiving production traffic.
      # terminationGracePeriodSeconds: 150

      nodeSelector:
        mlab/type: 'platform'
      containers:
        - name: ndt-cloud
          image: measurementlab/ndt-cloud:v0.1
          ports:
          - containerPort: 3010
          - containerPort: 9090
          volumeMounts:
          - name: ndt-certificates
            mountPath: /certs
            readOnly: true
      volumes:
      - name: ndt-certificates
        secret:
          secretName: ndt-certificates
